name: Release CI
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - uses: c-hive/gha-yarn-cache@v1

      - name: install
        run: yarn

      - name: Test
        run: yarn test
        env:
          # 百度配置项
          BAIDU_APP_ID: ${{ secrets.BAIDU_APP_ID }}
          BAIDU_KEY: ${{ secrets.BAIDU_KEY }}

          # 有道配置项
          YOUDAO_COOKIE: ${{ secrets.YOUDAO_COOKIE }}
          YOUDAO_TOKEN: ${{ secrets.YOUDAO_TOKEN }}
          YOUDAO_USER_AGENT: ${{ secrets.YOUDAO_USER_AGENT }}
          YOUDAO_APP_ID: ${{ secrets.YOUDAO_APP_ID }}
          YOUDAO_KEY: ${{ secrets.YOUDAO_KEY }}

          # 腾讯配置项
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
